spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://letsroll-db.cic2upy9gfyn.ap-northeast-2.rds.amazonaws.com/letsroll
    username: ENC(snvTheBGWWkrMtOiltwvog==)
    password: ENC(Keo/hnyyLmwMctIC4yzJ8FNjg0DLUSUt34Ce5VIsEKA=)

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  profiles:
    include: secret

  mvc:
    hiddenmethod:
      filter:
        enabled: true


